---
server:
  port: 8082


reply:
  message: Pong local

security:
  basic:
    enabled: false

enpoints:
  shutdown:
    sensitive: false
  autoconfig:
    sensitive: false
  info:
    sensitive: false
  health:
    sensitive: false
  env:
    sensitive: false