---
server:
  port: 8080

samplepong:
  ribbon:
    DeploymentContextBasedVipAddresses: sample-cloud-services-pong
    ReadTimeout: 5000
    MaxAutoRetries: 2
    IsSecure: true


another:
  key: anotherkeyvalue

security:
  basic:
    enabled: false

hystrix:
  command:
    pongClient:
      circuitBreaker:
        sleepWindowInMilliseconds: 5000
